[package]

name = "hoare"
version = "0.1.1"
authors = [ "nrc@ncameron.org" ]
description = "Design by contract style assertions for Rust"
repository = "https://github.com/nick29581/libhoare"
readme = "readme.md"

[[lib]]

name = "hoare"
crate_type = ["dylib"]
path = "libhoare/lib.rs"
plugin = true
